DROP TABLE IF EXISTS `acrit_import_profile`;
CREATE TABLE `acrit_import_profile` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` char(1) NOT NULL DEFAULT 'Y',
  `NAME` varchar(100) DEFAULT NULL,
  `CODE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ENCODING` varchar(100) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `TIMESTAMP_X` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `START_LAST_TIME` datetime DEFAULT NULL,
  `IBLOCK_ID` int(11) NOT NULL,
  `DEFAULT_SECTION_ID` int(11) NOT NULL,
  `SOURCE` varchar(255) NOT NULL,
  `SOURCE_TYPE` varchar(255) DEFAULT NULL,
  `SOURCE_LOGIN` varchar(255) DEFAULT NULL,
  `SOURCE_KEY` varchar(255) DEFAULT NULL,
  `SOURCE_DELIMITER` varchar(255) DEFAULT NULL,
  `SOURCE_ROOT_LEVEL` int(11) NOT NULL,
  `SOURCE_ROOT_ITEM` varchar(255) DEFAULT NULL,
  `SOURCE_PARAM_1` varchar(255) DEFAULT NULL,
  `SOURCE_PARAM_2` varchar(255) DEFAULT NULL,
  `SOURCE_PARAM_3` mediumtext DEFAULT NULL,
  `ELEMENT_IDENTIFIER` varchar(255) NOT NULL,
  `IMGS_SOURCE_TYPE` varchar(50) NOT NULL,
  `IMGS_SOURCE_PATH` varchar(255) NOT NULL,
  `ACTIONS_NOT_IN_FILE` varchar(50) NOT NULL,
  `ACTIONS_NEW_ELEMENTS` varchar(50) NOT NULL,
  `ACTIONS_EXIST_ELEMENTS` varchar(50) NOT NULL,
  `ACTIONS_PRICE_NULL` char(1) NOT NULL DEFAULT 'N',
  `ACTIONS_AMOUNT_NULL` char(1) NOT NULL DEFAULT 'N',
  `ACTIONS_SECTIONS_LINK` varchar(50) NOT NULL,
  `ACTIONS_SECTIONS_CREATE` char(1) NOT NULL DEFAULT 'Y',
  `ACTIONS_IB_IMG_MODIF` char(1) NOT NULL DEFAULT 'N',
  `SCHEDULE_DURATION` int(11) NOT NULL,
  `SCHEDULE_PERIOD` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
);


DROP TABLE IF EXISTS `acrit_import_profile_fields`;
CREATE TABLE `acrit_import_profile_fields` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PARENT_ID` int(10) unsigned NOT NULL,
  `F_FIELD` varchar(255) NOT NULL,
  `IB_FIELD` varchar(255) NOT NULL,
  `PARAMS` longtext,
  PRIMARY KEY (`ID`)
);